import re
from typing import Any, Dict, List


# Ingestion appends one `[image_description: ...]` block per unique image
# description at the end of `enhanced_text` (see data_process pipeline
# `_build_enhanced_chunk_text`).  Descriptions themselves contain "]" and
# newlines, so anchor each block on the next marker or end-of-string instead
# of matching a non-bracket run.
_IMAGE_DESCRIPTION_BLOCK_RE = re.compile(
    r"\[image_description:\s*(.+?)\]\s*(?=\n\n\[image_description:|\s*\Z)",
    flags=re.DOTALL,
)

# Descriptions are generated by a vision model and open with a recognizable
# boilerplate lead-in whose parenthesized group is often the figure title.
_DESCRIPTION_LEAD_IN_RE = re.compile(
    r"^\s*(?:根据)?您提供的(?:[一二三四五六七八九十\d]+张)?(?:图片|图纸|图像|图则|图)\s*"
    r"(?:[（(]\s*(?:标题为)?\s*[“\"']?(?P<title>.+?)[”\"']?\s*[)）])?",
    flags=re.DOTALL,
)

# The remainder of the boilerplate framing that precedes real content, e.g.
# "及上下文信息，以下是对该图在...的专业解读："
_BOILERPLATE_TAIL_RE = re.compile(
    r"^\s*(?:[，,、]|及|结合|和|与)?\s*"
    r"(?:上下文(?:信息|文字|说明)?|文字说明|说明|图例|表格片段|标注)*\s*[，,：:]?\s*",
)

# A sentence that actually states what the figure is.
_FIGURE_IDENTITY_RE = re.compile(
    r"(?:该图片?|本图|此图|图纸|该图纸|该规划图)\s*(?:为|是|属于|展示|呈现|描绘|表达)\s*(?P<body>[^\n。！？；;]{6,})",
)

# Quoted/bracketed figure titles, e.g. 《...控制图则》 or “空中连接体控制图”.
# Scanned only over the opening clause, and required to name a drawing — deeper
# in the description the same quoting style wraps section labels and slogans.
_QUOTED_TITLE_RE = re.compile(r"[《“\"'](?P<title>[^》”\"'\n]{6,60})[》”\"']")
_DRAWING_TITLE_TOKENS = ("图", "图则", "表", "导则", "指南", "标准", "规范", "示意", "流程")

# Groups that describe the model's *inputs* rather than name the figure.
_NON_TITLE_PREFIX_RE = re.compile(r"^\s*(?:含|结合|其中|前两张|附|另|以及|和|与|及)")

# Leading connectives/particles left over once boilerplate framing is removed.
_LEADING_PARTICLE_RE = re.compile(
    r"^\s*(?:[，,、：:]|及|结合|和|与|的是|的|是|为|属于|内容|上下文|文材料|文字说明|说明)+\s*"
)

# Phrases that mean the sentence is the model talking about its own answer
# rather than describing the figure.
_META_COMMENTARY_TOKENS = (
    "您提供", "以下是", "现对", "现从", "如下", "专业解读", "专业解析", "系统性解读",
    "进行解读", "无法直接查看", "尽管无法", "文字说明", "上下文", "表格片段",
    "图例参考", "重点聚焦", "本回答", "以上",
)

# Placeholder descriptions written when ingestion could not describe an image.
_UNUSABLE_DESCRIPTIONS = {"[图片文件未找到]", "[无法生成描述]", "图片文件未找到", "无法生成描述"}

# "三张图片（图1–图3）" style titles identify nothing specific.
_GENERIC_TITLE_RE = re.compile(r"^[图\s\d—–\-~至和、,，与及]+$")

_MARKDOWN_NOISE_RE = re.compile(r"[*`#>]+")


def extract_image_descriptions(enhanced_text: str) -> List[str]:
    """Parse ordered ``[image_description: ...]`` blocks from a chunk's enhanced text.

    Returned in document order.  Note the ingestion pipeline de-duplicates by
    description text, so a chunk with N images may yield fewer than N blocks —
    callers must align by index and tolerate missing entries rather than
    assuming a 1:1 mapping.
    """
    text = str(enhanced_text or "")
    if "[image_description:" not in text:
        return []

    out: List[str] = []
    for match in _IMAGE_DESCRIPTION_BLOCK_RE.finditer(text):
        body = (match.group(1) or "").strip()
        if not body or body in _UNUSABLE_DESCRIPTIONS:
            out.append("")
            continue
        out.append(body)
    return out


def summarize_image_description(description: str, max_chars: int = 120) -> str:
    """Condense a verbose image description into a one-line semantic hint.

    Full descriptions run ~800 characters of multi-section markdown, which would
    crowd out the retrieved text if injected wholesale into the prompt.  The
    vision model's opening line names the figure, so prefer that title and fall
    back to the leading clause.
    """
    raw = str(description or "").strip()
    if not raw or raw in _UNUSABLE_DESCRIPTIONS:
        return ""

    lead_in = _DESCRIPTION_LEAD_IN_RE.match(raw)

    # Candidates in descending preference; first one that survives the
    # meta-commentary filter wins.
    candidates: List[str] = []

    # 1) The figure title the model put in parentheses after "您提供的图片".
    if lead_in:
        candidates.append(_MARKDOWN_NOISE_RE.sub("", lead_in.group("title") or ""))

    # 2) A quoted/bracketed title in the opening clause that names a drawing.
    opening = re.split(r"[。！？\n]", raw, maxsplit=1)[0]
    for match in _QUOTED_TITLE_RE.finditer(opening):
        title = _MARKDOWN_NOISE_RE.sub("", match.group("title") or "")
        if any(token in title for token in _DRAWING_TITLE_TOKENS):
            candidates.append(title)

    # 3) An explicit "该图为 ..." identity statement.
    body = raw[lead_in.end():] if lead_in else raw
    body = _BOILERPLATE_TAIL_RE.sub("", body, count=1)
    for source in (body, raw):
        identity = _FIGURE_IDENTITY_RE.search(source)
        if identity:
            candidates.append(_MARKDOWN_NOISE_RE.sub("", identity.group("body") or ""))

    # 4) Last resort: the first prose clause, minus markdown scaffolding.
    first_block = re.split(r"\n\s*(?:-{3,}|#{1,6}\s|\d+[.、]\s|[-*+]\s)", body or raw, maxsplit=1)[0]
    candidates.append(_MARKDOWN_NOISE_RE.sub("", re.split(r"(?<=[。！？；;])|\n", first_block, maxsplit=1)[0]))

    for candidate in candidates:
        cleaned = _clean_description_candidate(candidate)
        if cleaned:
            return _clip_text(cleaned, max_chars)
    return ""


def build_image_semantic_hint(
    *,
    description: str = "",
    figure: str = "",
    caption: str = "",
    name: str = "",
    ordinal: int = 1,
    caption_is_usable: bool = True,
    name_is_usable: bool = True,
) -> str:
    """Pick the best available semantic hint for one image, in preference order.

    The vision-generated description is by far the most informative source; the
    markdown-derived figure label and caption are used when present, and the
    filename is a last resort (OCR output usually names files by content hash,
    so callers pass ``name_is_usable=False`` for those).
    """
    summarized = summarize_image_description(description)
    fig = str(figure or "").strip()
    cap = str(caption or "").strip() if caption_is_usable else ""
    nm = str(name or "").strip() if name_is_usable else ""

    if summarized:
        # Keep the document's own figure label when it adds locating value.
        if fig and fig not in summarized:
            return f"{fig} {summarized}"
        return summarized

    if fig and cap and fig not in cap:
        return f"{fig} {cap}"
    return cap or fig or nm or f"图片{ordinal}"


def _clean_description_candidate(raw_candidate: str) -> str:
    """Normalize a candidate hint, returning "" when it is not figure semantics."""
    text = _collapse_whitespace(raw_candidate)
    # Strip leading connectives/particles left behind by boilerplate removal.
    text = _LEADING_PARTICLE_RE.sub("", text)
    text = text.strip(" 　，,、；;：:。.“”\"'()（）《》")
    if len(text) < 5:
        return ""
    if _GENERIC_TITLE_RE.match(text):
        return ""
    if _NON_TITLE_PREFIX_RE.match(text):
        return ""
    if any(token in text for token in _META_COMMENTARY_TOKENS):
        return ""
    return text


def _collapse_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip()


def _clip_text(text: str, max_chars: int) -> str:
    s = str(text or "").strip()
    if max_chars <= 0 or len(s) <= max_chars:
        return s
    return s[:max_chars].rstrip() + "…"


def extract_query_keywords_for_image_boost(query: str) -> List[str]:
    """Extract a few high-signal keywords from a Chinese query."""
    s = re.sub(r"[\s，,。.!！?？;；:：()（）\\[\\]{}<>《》\"'`/\\\\|]+", " ", (query or "").strip())
    s = re.sub(
        r"(请问|请|帮我|一下|麻烦|能否|可以|是否|什么是|是什么|指什么|什么意思|如何|为什么|多少|怎么|定义|含义)",
        " ",
        s,
    )
    s = s.replace("的", " ")
    parts = [p.strip() for p in s.split() if p.strip()]

    kws: List[str] = []
    for p in parts:
        for m in re.findall(r"[\u4e00-\u9fff]{2,}", p):
            kws.append(m)
        for m in re.findall(r"[A-Za-z0-9]{2,}", p):
            kws.append(m)

    uniq = sorted(set(kws), key=lambda x: (-len(x), x))
    return uniq[:10]


def ranked_results_contain_relevant_images(results: List[Dict[str, Any]], query: str) -> bool:
    """Return True when there is at least one image-bearing result likely relevant to the query."""
    kws = extract_query_keywords_for_image_boost(query or "")
    if not kws:
        kws = []

    for r in results or []:
        try:
            meta = r.get("metadata", {}) or {}
            text = str(r.get("text") or "")
            has_img = meta.get("has_image") is True or "![" in text
            if not has_img:
                continue
            if not kws:
                return True

            hay = (text or "").replace(" ", "")
            if any(kw in hay for kw in kws[:6]):
                return True
        except Exception:
            continue
    return False


def search_image_chunks_by_text(*, mongo, query: str, limit: int = 2) -> List[Dict[str, Any]]:
    """Best-effort Mongo text search over chunks, restricted to has_image=True."""
    q = (query or "").strip()
    if not q or mongo is None:
        return []

    docs = []
    try:
        docs = mongo.text_search("chunks", q, limit=limit, filter_query={"has_image": True})
    except Exception:
        try:
            keywords = extract_query_keywords_for_image_boost(q)
            if keywords:
                or_clauses = []
                for kw in keywords[:4]:
                    safe = re.escape(kw)
                    or_clauses.append({"text": {"$regex": safe}})
                    or_clauses.append({"enhanced_text": {"$regex": safe}})
                docs = mongo.find_by_query(
                    "chunks",
                    {"has_image": True, "$or": or_clauses},
                    limit=limit,
                    projection={
                        "_id": 1,
                        "doc_id": 1,
                        "chunk_index": 1,
                        "text": 1,
                        "enhanced_text": 1,
                        "section_title": 1,
                        "has_image": 1,
                        "has_table": 1,
                        "file_name": 1,
                        "category": 1,
                        "page": 1,
                        "page_end": 1,
                    },
                )
        except Exception:
            return []

    boosted: List[Dict[str, Any]] = []
    for doc in docs or []:
        chunk_id = str(doc.get("_id") or "").strip()
        text = str(doc.get("text") or doc.get("enhanced_text") or "").strip()
        if not chunk_id or not text:
            continue

        boosted.append(
            {
                "id": chunk_id,
                "source": "keyword",
                "text": text,
                "doc_id": doc.get("doc_id"),
                "chunk_index": doc.get("chunk_index"),
                "metadata": {
                    "file_name": doc.get("file_name", ""),
                    "category": doc.get("category", ""),
                    "section_title": doc.get("section_title", ""),
                    "has_table": bool(doc.get("has_table")),
                    "has_image": bool(doc.get("has_image")),
                    "page": doc.get("page"),
                    "page_end": doc.get("page_end"),
                },
                "score": float(doc.get("score") or 0.65),
            }
        )

    return boosted
